"""Criada a tabela Passageiros e a localizacao e reformulada a tabela rotas

Revision ID: 9359df43e721
Revises: b4c657f39347
Create Date: 2022-11-06 12:20:50.975123
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9359df43e721'
down_revision = 'b4c657f39347'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'localizacao',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('localizacao', sa.String(length=60), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'passageiros',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('qtd_interesse', sa.SmallInteger(), nullable=False),
        sa.Column('qtd_pessoas', sa.SmallInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'rota',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('nome', sa.String(length=60), nullable=False),
        sa.Column('bus_id', sa.BigInteger(), nullable=False),
        sa.Column('localizacao_id', sa.BigInteger(), nullable=False),
        sa.Column('passageiros_id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['bus_id'],
            ['bus.id'],
        ),
        sa.ForeignKeyConstraint(
            ['localizacao_id'],
            ['localizacao.id'],
        ),
        sa.ForeignKeyConstraint(
            ['passageiros_id'],
            ['passageiros.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rota')
    op.drop_table('passageiros')
    op.drop_table('localizacao')
    # ### end Alembic commands ###
